# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 357790c87cc362afcc68af3b24d201d7ae86e0d021cbc7a39ab1074e3f83e8925c90497226bb717e8c529dec37795e680eeb0e255eedb27fabfc17396248ed19

test:
  secret_key_base: 6043e8e28a5d38c88484367f99c757cc51a033bf87afa4d6f93518900e7e6583bb8cb932000c48edc9f68f618ae82d10e4248cb4d2aa7818f11b46ad90643348

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
